services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ferdyrurka\SingleTenantVendorClient\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

  Ferdyrurka\SingleTenantVendorClient\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  Ferdyrurka\SingleTenantVendor\Repository\OrderRepositoryInterface: '@Ferdyrurka\SingleTenantVendorClient\Repository\OrderRepository'
